// Code generated by "stringer -type=WalletType -linecomment"; DO NOT EDIT.

package binance

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpotWallet-1]
	_ = x[IsolatedMarginWallet-2]
}

const _WalletType_name = "SPOTISOLATED_MARGIN"

var _WalletType_index = [...]uint8{0, 4, 19}

func (i WalletType) String() string {
	i -= 1
	if i < 0 || i >= WalletType(len(_WalletType_index)-1) {
		return "WalletType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _WalletType_name[_WalletType_index[i]:_WalletType_index[i+1]]
}
